### ISSUE TITLE
Add a README

### ISSUE THREAD

**Issue by gomezzz** [aidotse/PASEOS#6]
# Feature
## Desired Behavior / Functionality
We need a more comprehensive readme, similar to e.g. https://github.com/esa/torchquad/

## What Needs to Be Done
- [x] Expand readme.md, e.g. by stealing some stuff from [torchquad](https://github.com/esa/torchquad/blob/main/README.md) 
- [x] Add example how to add an activity that does something (could also be done in #24 )
- [x] Add example how to add comms devices, power
- [x] Add example how to charge power
- [x] Add example how to log performance (could also be done in #18 )
- [x] Add example how to visualize current simulation (could also be done in #11 #27 )
- [x] Add example showcasing that paseos is meant to run on the actual devices (or emulations thereof). Right now, users may think paseos is a central simulation
- [x] Add installation instructions for pip and conda
- [ ] Add example how to perform parallel activities within one activity

**Comment by gomezzz** [comment]
- [ ] Add a diagram overview of the codebase
- [ ] Some initial description

**Comment by gomezzz** [comment]
On initial images in #10 
- What is an actor
- Explain what activities are

**Comment by vinuthams** [comment]
**Enhance working diagram for simulation** 

Paseos simulates env for operating multiple spacecrafts (sc)..
This could be used in conjunction with a learning framework, communication layer, a decision layer to build an/several application 

- contains actors
- environment constraints [speed, radiation, gravity(?) etc. that are physical laws..that we want to explicitly put in ]
- each actor can conduct a number of activities [ping hello, train, push, execute model, send decision ]
- each actor has same set of constraints [battery , memory , sun (?) ]
- each actor has same set of properties ? [velocity, trajectory parameters etc ]
- triggers for activity in each actor , [line of sight, also from layers above or below ]
-
- 

**Imagined working of Paseos**

Initial setup of the simulation:
Register actors 
Initialise constraints, set properties ( unique to actor? )
Start shared clock 
each actor does an activity , 
  on trigger , conducts an activity 
until stop condition of simulation 

On diagram as it is now : 
Mixes up the instance of the software , with the functionality of the software itself. 
( i.e actors == devices )

**Comment by gomezzz** [comment]
Parts will be done now in #65

**Comment by gomezzz** [comment]
Closing for now as almost everything is done, can re-open if necessary
